### ISSUE TITLE
[Bug] LOAD and UNLOAD buttons do not cause the extruder to work

### ISSUE THREAD

**Issue by leckert123** [Phil1988/FreeDi#13]
Using V1.02

**The LOAD and UNLOAD buttons do not work from the screen. **

1. I preheat the nozzle, and when it reaches something resembling hot, like > 200C the LOAD, UNLOAD buttons go from gray to blue
2. Hitting the buttons - the extruder icon animates, like it's doing something, but nothing actually happens. The extruder doesn't operate. 
4. Those actions **generally** work from Mainsail webUI macro buttons.  Again, with pre-heating first. I wasn't sure if it was a Klipper issue or not, which is why I tried it also from the webUI.  A couple of times it did not seem to work, but I think it was because I had not completely preheated the nozzle.
5. My manual workaround - I heat the nozzle until it hits the temp I want, then I use the arrows with 50mm to extrude the filament. Honestly, I prefer this.

**Comment by Phil1988** [comment]
1. Is expected and correct. The "unlock" temp is 180°C to prevent damages while attempting cold extrusion.

2. Information here is not sufficient. For the future please add more detailed information to save my time. 
You showed me a video (via discord) where its visible that the target temp is set to 215°C after you hit the "load" button. 
So the button does work.
You simply hit the button multiple times while it was not yet at the target temp + hitting other buttons and you took wrong assumtions.

3. This works **also** from the Mainsail WebUI. 
There you simply had more paitience.
Preheating is not neccesary, as this is what the load/unload macro does.

4. You can do that, but its not a **workaround**. The button works as expected. It does multiple things like heating to a certain temp, wait for it, extruding in different speed stages etc. - Thats exactly what a macro is for.
You are free to do every single step manually and wait for each step to complete before doing the next.
But that is not a "workaround", its just performing the exact macro manually instead if patiently waiting for it to do it automatically.

I close this, as its not at all a bug - and its also not linked to my software, but to the fact how macros work in klipper.

**Comment by leckert123** [comment]
My fault for not explaining that in the 1st step, the LOAD and UNLOAD buttons were grayed out and inactive, unless I preheated the hot end.  Covered in a new bug report. Thank you for your patience.
