### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by boromyr** [Phil1988/FreeDi#18]
Hello, with your mods, firmware and screen, would it be possible to recover the print after a power outage?

**Comment by Phil1988** [comment]
If you find a way to make this work with klipper: yes.
Otherwise, I dont have included any feature like that.

**Comment by boromyr** [comment]
I've seen several klipper scripts that implement prl, I was wondering if you added something like that. Does the bed go down by itself when you turn off the printer?

**Comment by Phil1988** [comment]
No it doesnt.

Can you show me a good realization of a prl please? 
So I can see how it might be possible.
