### ISSUE TITLE
Klipper fails to start after fresh installation on X Max 3

### ISSUE THREAD

**Issue by colin-small** [Phil1988/FreeDi#19]
I am using a 32GB EMMC card on my X Max 3 and I used win32img to write the latest release to it as the wiki instructs to do.

It seemed to successfully write the OS to the card and it booted as expected and the stock display displayed the expected error because the screen was not flashed.

I copied the latest screen firmware to the microSD card and placed it in the screen and it flashed as the wiki said it would.

After the successful screen flash I powered off the machine with the power switch, waited 30 seconds and powered it back on.

The screen displayed the new firmware as expected.

It tries to start klipper and takes a while but eventually fails simply stating that klipper failed to start and tells me to restart klipper.

I tap restart klipper and it tries again and fails, now says please restart firmware.

I tap restart firmware and it eventually fails to restart klipper again.

I tried powering off the machine and powering it back on.

I tried several attempts of just restarting klipper hoping for the best, but nothing works.

What could be wrong and how can I resolve the issue? At the moment I have no access to the printer because klipper is failing and I can't configure WiFi.. I could connect an Ethernet cable but it will be a challenge due to physical distance.. I could connect a cable directly to a laptop but I'm not sure if the firmware assigns any sort of default IP or if I would need to run a dhcp service on the laptop to give it an ip. If I have to I will physically move the printer to a place that I can get dhcp.

**Comment by Phil1988** [comment]
Hey @colin-small ,
Im glad you could solve it.

Can you please share what was the problem exactly?

I think it was:
You had no network connection, so you couldnt finish the terminal/ssh parts of the guide.
Is that true and the only problem?

And I think I did not state that a ethernet connection is needed, but I simply have missed it, because I am using a wired connection.

I will think about a work that might work even if no ethernet connection is possible.

**Comment by colin-small** [comment]
@Phil1988 Yes, that was the issue. I proceeded with the installation not realizing that I would need the Ethernet connection to complete it.

My printer is only accessible via WiFi due to its location.

Using an old WiFi router to create a new SSID and plugging the printer Ethernet directly into that router allowed me to connect to it with a laptop and complete the steps.

Great job by the way. Really nice work here. Thank you for making this!

**Comment by Phil1988** [comment]
Im happy that you like it :)
If you want to support this, feel free to give this project a star or a small donation :)

**Comment by Phil1988** [comment]
Just to complete this:
The "wired connection" has been placed at the wiki https://github.com/Phil1988/FreeDi/wiki/Requirements
