### ISSUE TITLE
[Bug] Exception errors on running start.py, touchscreen not working

### ISSUE THREAD

**Issue by jarretluft** [Phil1988/FreeDi#2]
Hi,
I have a Qidi X-Plus 3 with 32mb emmc.

I have followed the step by step guide you produced for FreeQIDI to get to a standard bookworm install with klipper, moonraker, fluidd and crowsnest.

I have then followed the wiki to install FreeDI screen.
I am using the **X3seriesLCD_firmware_v1.01.tft** screen firmware

I have followed the **"installation guide for existing systems"** to install FreeDI

All of this completed without any issues, and then I rebooted and the X3SeriesLCD service started and the screen is working, but the touch is not.  Have you had any issues with the touch screen not accepting input?

Any ideas what could be wrong here?
Thank you!

_Edit: removed error that was caused by me trying to run python3 start.py after the x3serieslcd service had already started, it is not related to the issue of screen input not being recognized._

**Comment by jarretluft** [comment]
After further troubleshooting, I think this is an issue with the cable that connects the touch screen overlay to the LCD.  I have removed the LCD, removed/reattached the cable and reinstalled, and things are working as expected now.  Sorry for the bother.

**Comment by Phil1988** [comment]
I am happy you find the error and that you are using the firmware.
I hope it gives you a nice user experience and you like it!
