### ISSUE TITLE
[Update Manager] Safe to use with the firmware?

### ISSUE THREAD

**Issue by colin-small** [Phil1988/FreeDi#20]
Pardon my ignorance, but is it safe to use update manager to update all of the components and packages that are listed as having updates available?

Or does it need to stay at the versions from the firmware release and be upgraded via the firmware process etc?

I can see mainsail and 39 system packages are able to be upgraded via update manager.

Is it safe to just "update all components" in the mainsail update manager UI?

**Comment by Phil1988** [comment]
Hey @colin-small ,

Yes you can safely update all of those as I have tested that.
Good reason to have my solution with an open system is that you are free on mainline software :)

Just a hint: Some updates can break things.
This is not connected to my firmware/software solution but to klipper in general.
But if anything breaks, it can be fixed :)
So even if support of qidi reaches EOL you will have an up to date system :)
