### ISSUE TITLE
[Feature request] Guide for XSmart3 SOC 'mcu' and toolhead 'MKS_THR' firmware in wiki?

### ISSUE THREAD

**Issue by robonxt** [Phil1988/FreeDi#21]
After working till 4 am and taking a nap, I found out that it took a while to flash the toolhead's firmware. I had to dig to find the instructions, as it was in your FreeQIDI guide, and not in this repo's wiki. I also noticed that we have a 'mcu' device that is on an older klipper version, and I'm not sure if it requires update as well.

Here is a screenshot of the MCUs:

![image](https://github.com/user-attachments/assets/44397849-637d-4f3f-b053-e96d80224d98)

Could we have guides for both the 'mcu' and 'MKS_THR' in the wiki?

**Comment by robonxt** [comment]
I'm silly. it's already written here: https://github.com/Phil1988/FreeDi/wiki/Installation-guide-for-fresh-systems#2-your-mainboard-mcu-and-the-toolhead-are-not-on-klipper-v0120-289---and-you-want-it-the-easy-way

Closing this.

**Comment by Phil1988** [comment]
I was about to give you the link, but I see you found it :)
I know there is much information in the wiki and sometime hard to find.
