### ISSUE TITLE
[Bug] WiFi not working

### ISSUE THREAD

**Issue by chrizbee** [Phil1988/FreeDi#23]
**Describe the bug**
Wired connection is working fine. Network settings on display show nothing at all for wireless.
For my printer no RTL8188GU dongle is used. Output for `lsusb`:

```
Bus 002 Device 002: ID a69c:5721 aicsemi Aic MSC
```

I've already tried the usb_modeswitch from [here](https://linux.brostrend.com/advanced/usb_modeswitch/) but `ip a` always only shows loopback and end1 (ethernet).

**Comment by chrizbee** [comment]
I've installed the newest version on X Max 3 just yesterday.

- X3seriesLCD firmware version: X3seriesLCD_firmware_v1.03.tft
- OS: Armbian-unofficial 24.2.0-trunk bookworm
- Host: v0.12.0-289-g08a1c9f12
- Source: FreeDi image [from here](https://github.com/Phil1988/FreeDi/releases/tag/v1.03)
- Mainboard: Stock Mainboard X-6 V1.0

> The RTL8188GU dongle is definetly working, as I have included and tested it.

That's not my problem (my phrasing was a little bit off). I meant that I **don't** have the RTL8188GU dongle. In your install.sh you use:
```bash
# Find vendor_id and product_id for RTL8188GU
echo "Finding vendor_id and product_id for RTL8188GU"
device_info=$(lsusb | grep -i "RTL8188GU")
```

but as mentioned before, `lsusb` only outputs the following:

```
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 003: ID 2604:0013 Tenda AIC8800DC
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 004 Device 003: ID 1bcf:0b09 Sunplus Innovation Technology Inc. HD Camera
Bus 004 Device 002: ID 1a40:0101 Terminus Technology Inc. Hub
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 1d50:614e OpenMoko, Inc. rp2040
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by Phil1988** [comment]
Is this a wifi dongle that qidi did ship with your machine?

**Comment by chrizbee** [comment]
Yes it is - it was working on the stock image.

If nothing helps I might go back to the old EMMC and try to check for the dongle's driver - or just use another dongle if I find one...

**Comment by chrizbee** [comment]
Working now.

I installed the driver from the manufacturers homepage:
https://www.tendacn.com/de/download/detail-5294.html

The correct modeswitch is:
```bash
sudo usb_modeswitch -KQ -v a69c -p 5721
```

To run automatically I created a udev rule:
```bash
sudo nano /etc/udev/rules.d/99-usb_modeswitch.rules
```
```
ACTION=="add", ATTR{idVendor}=="a69c", ATTR{idProduct}=="5721", RUN+="/usr/sbin/usb_modeswitch -v a69c -p 5721 -KQ"
```

Then reload udev rules or reboot:
```
sudo udevadm control --reload
```

and voila
```
3: wlxc83a3528c58c: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
```

**Comment by Phil1988** [comment]
Thanks @chrizbee for that report.
It is very tiring that Qidi is constantly changing hardware components across a printer series within the same model/version.

I will reopen this to have deeper look at it.
My goal is to automatically detect and support the right wifi dongle.

I might ask you something in the future (for testing of problems) if thats fine for you :)

**Comment by chrizbee** [comment]
> It is very tiring that Qidi is constantly changing hardware components across a printer series within the same model/version.

super annoying... I also had to add the fan "fix" - same version, different hardware...

> I might ask you something in the future (for testing of problems) if thats fine for you :)

Fine by me. But the Qidi printer is used at work - so after this week I'm only back in January.

**Comment by Phil1988** [comment]
Its not on the "super high priority list" for me.
Currently I'm working hard on the next release :)

**Comment by Phil1988** [comment]
Im wondering if the /etc/udev/rules.d/99-usb_modeswitch.rules is necessary for you?
For the RTL8188GU its a one time thing to set the mode switch.

You also set the option `-K`.
In the past this was:
`-K: Keep the device in the new mode`
currently this is
`-K: send standard EJECT sequence`
Are you aware of that?

Would be nice to just set it once with no need to use an automated udev rule.

**Comment by Phil1988** [comment]
I have adjusted my script and hope this will work.
As I dont own your dongle, I cant test it.
Here is the bash:
```
# Console output
echo "Installing WiFi..."

# Update package lists
sudo apt-get update

# Install usb-modeswitch
sudo apt-get install -y usb-modeswitch || {
    echo "Failed to install usb-modeswitch."
    exit 1
}

# Check for connected USB devices and identify the WiFi chip
echo "Detecting WiFi chip..."

# Find RTL8188GU device
device_info_rtl=$(lsusb | grep -i "RTL8188GU")

# Find AIC8800DC device
device_info_aic=$(lsusb | grep -i "a69c:5721")

if [ -n "$device_info_rtl" ]; then
    echo "RTL8188GU detected."
    vendor_id=$(echo $device_info_rtl | awk '{print $6}' | cut -d: -f1)
    product_id=$(echo $device_info_rtl | awk '{print $6}' | cut -d: -f2)
    echo "vendor_id: $vendor_id, product_id: $product_id"

    # Configure the USB WLAN dongle
    sudo usb_modeswitch -v $vendor_id -p $product_id -J

    # Copy the firmware file
    sudo cp wifi/rtl8710bufw_SMIC.bin /lib/firmware/rtlwifi/
    echo "WiFi installation for RTL8188GU completed!"

elif [ -n "$device_info_aic" ]; then
    echo "AIC8800DC detected."
    vendor_id=$(echo $device_info_aic | awk '{print $6}' | cut -d: -f1)
    product_id=$(echo $device_info_aic | awk '{print $6}' | cut -d: -f2)
    echo "vendor_id: $vendor_id, product_id: $product_id"

    # Configure the USB WLAN dongle for AIC8800DC
    sudo usb_modeswitch -KQ -v $vendor_id -p $product_id

    # Create udev rule to handle future connections automatically
    echo "Creating udev rule for AIC8800DC..."
    echo "ACTION==\"add\", ATTR{idVendor}==\"$vendor_id\", ATTR{idProduct}==\"$product_id\", RUN+=\"/usr/sbin/usb_modeswitch -v $vendor_id -p $product_id -KQ\"" | sudo tee /etc/udev/rules.d/99-usb_modeswitch.rules

    # Reload udev rules
    sudo udevadm control --reload
    echo "WiFi installation for AIC8800DC completed!"

else
    echo "No supported WiFi chip detected. Please ensure the device is connected."
fi
```

**Comment by Phil1988** [comment]
Any news on this @chrizbee ?
I received 2 dongles that I bought to test and develop, but unfortunately these don't use the AIC8800DC :(

I think I won't buy any more.

**Comment by billkenney** [comment]
Someone posted a similar issue on my repository (https://github.com/billkenney/update_max3_plus3/issues/6#issuecomment-2173931086). They were able to get it working by following this guide: https://forum.beagleboard.org/t/success-with-brostrend-usb-wifi-dongle-somewhere-to-document-the-process/37007/3

**Comment by Phil1988** [comment]
Thank @billkenney
Can you tell me why this approach is better in your opinion than the solution here?

I will hope for a response of @chrizbee to see if the install script does work.

**Comment by billkenney** [comment]
> Thank @billkenney
> 
> Can you tell me why this approach is better in your opinion than the solution here?
> 
I don't have the AIC card so I don't know what works. I just saw this yesterday and was trying to be helpful in the event your script doesn't work. If your script does work I'd say it's much better.

**Comment by Phil1988** [comment]
> I don't have the AIC card so I don't know what works. I just saw this yesterday and was trying to be helpful in the event your script doesn't work. If your script does work I'd say it's much better.

Thanks for your support :)

**Comment by chrizbee** [comment]
Today I'm back from vacation - first of all Happy New Year and thanks for the FreeDi 1.20 update!

I've just now tested the update script - it works like a charm!

What I did was:
- Remove my `99-usb_modeswitch.rules`
- Uninstall the `ax300-wifi-adapter-linux-driver`
- Reboot
- Run the wifi bash script

What I would add to your script (which seems to be the automated version of my manual solution):
1. Still installing the driver when no usb_modeswitch is needed
```
Bus 002 Device 003: ID 2604:0013 Tenda AIC8800DC
```
```bash
# Find AIC8800DC mass storage device
device_info_aic=$(lsusb | grep -i "a69c:5721")

# Find AIC8800DC wifi device
device_info_aic_wifi=$(lsusb | grep -i "2604:0013")
```

2. Optional: Maybe switch from the seperate udev rule to `/etc/mod_switch.conf`

**Comment by Phil1988** [comment]
Thanks a lot for testing/feedback it and your suggestions to improve it 👍 

> (which seems to be the automated version of my manual solution)
Why should I reinvent the wheel if you have already established a nice way ? :)
I cant test it, so I rely on users feedback anyway.

I also integrated your /etc/mod_switch.conf suggestion:
```
# Check for connected USB devices and identify the WiFi chip
echo "Detecting WiFi chip..."

# Find RTL8188GU device
device_info_rtl=$(lsusb | grep -i "RTL8188GU")

# Find AIC8800DC as mass storage device
device_info_aic_mass_storage=$(lsusb | grep -i "a69c:5721")

# Find AIC8800DC as wifi device
device_info_aic_wifi=$(lsusb | grep -i "2604:0013")

if [ -n "$device_info_rtl" ]; then
    echo "RTL8188GU detected."
    vendor_id=$(echo $device_info_rtl | awk '{print $6}' | cut -d: -f1)
    product_id=$(echo $device_info_rtl | awk '{print $6}' | cut -d: -f2)
    echo "vendor_id: $vendor_id, product_id: $product_id"

    # Configure the USB WLAN dongle
    sudo usb_modeswitch -v $vendor_id -p $product_id -J

    # Copy the firmware file
    sudo cp $FREEDI_LCD_DIR/wifi/rtl8710bufw_SMIC.bin /lib/firmware/rtlwifi/
    echo "WiFi installation for RTL8188GU completed!"

elif [ -n "$device_info_aic_mass_storage" ]; then
    echo "AIC8800DC detected as mass storage device."
    vendor_id=$(echo $device_info_aic_mass_storage | awk '{print $6}' | cut -d: -f1)
    product_id=$(echo $device_info_aic_mass_storage | awk '{print $6}' | cut -d: -f2)
    echo "vendor_id: $vendor_id, product_id: $product_id"

    # Configure the USB WLAN dongle for AIC8800DC
    sudo usb_modeswitch -KQ -v $vendor_id -p $product_id

    # Use /etc/mod_switch.conf instead of a udev rule
    echo "Updating /etc/mod_switch.conf..."
    echo "$vendor_id:$product_id -KQ" | sudo tee -a /etc/mod_switch.conf

    # Reload usb_modeswitch configuration
    sudo systemctl restart usb-modeswitch

    # Install the driver package
    echo "Installing driver package for AIC8800DC..."
    sudo dpkg -i $FREEDI_LCD_DIR/wifi/ax300-wifi-adapter-linux-driver.deb

    echo "WiFi installation for AIC8800DC completed!"

elif [ -n "$device_info_aic_wifi" ]; then
    echo "AIC8800DC detected in wifi mode."
    vendor_id=$(echo $device_info_aic_wifi | awk '{print $6}' | cut -d: -f1)
    product_id=$(echo $device_info_aic_wifi | awk '{print $6}' | cut -d: -f2)
    echo "vendor_id: $vendor_id, product_id: $product_id"

    # Install the driver package
    echo "Installing driver package for AIC8800DC..."
    sudo dpkg -i $FREEDI_LCD_DIR/wifi/ax300-wifi-adapter-linux-driver.deb

    echo "WiFi installation for AIC8800DC completed!"

else
    echo "No supported WiFi chip detected. Please ensure the device is connected."
fi
```

Would be nice if you can have a look at it again.
Thanks for your support!

**Comment by chrizbee** [comment]
This shouldn't work. The configuration is different to the cli paramters - that's why I didn't bother to switch from the udev rule to the config file. You can find the parameter reference here:
[https://www.draisberghof.de/usb_modeswitch/parameter_reference.txt](https://www.draisberghof.de/usb_modeswitch/parameter_reference.txt)

Maybe we should just keep the udev rule, since it's working? 😄

**Comment by Phil1988** [comment]
Yes I think so too  :)
I changed it back again
Thanks for your support!

I think this is finished now, so I will close it.

**Comment by MaZZly** [comment]
I ran the bash script from https://github.com/Phil1988/FreeDi/issues/23#issuecomment-2557067580 and after reboot I was able to connect to Wifi through the LCD also :) :+1:
