### ISSUE TITLE
[Not a bug] Upgrade to 1.20 failed on X-Max 3

### ISSUE THREAD

**Issue by colin-small** [Phil1988/FreeDi#25]
I was running the previous latest version of FreeDi, I saw the new release for 1.20 and I followed the update instructions on the wiki by modifying the printer config, cloning the repo, running the update script, and rebooting the printer. The screen showed it was flashing and then it failed with the following message.

![image](https://github.com/user-attachments/assets/40016cb1-cdb1-49c6-9e9d-d3fe226e0675)

Not sure what I should do now.

**Comment by Phil1988** [comment]
It might have been a transmission error during the update.
Have you shut the printer off and on again?

I havent seen this problem on my side but I am positive its nothing big.

For further help, can you give me this information:
**Base (please complete the following information):**
 - X3seriesLCD firmware version: [e.g. v1.00 stable]
 - OS: [e.g. Armbian-unofficial_24.2.0-trunk_Mkspi_bookworm_current_6.6.17]
 - Source: [eg. self configured or FreeDi image]
 - Mainboard: [eg. stock Mainboard X-4/X-6]

If it all fails you still can update the firmware via SD card with your matching file from here:
https://github.com/Phil1988/FreeDi/tree/master/screen_firmwares

But I would like to know and solve it the right way ;)

**Comment by colin-small** [comment]
I will try a simple restart again when I get home when I get home and let you know. Does this new version only affect the screen firmware or the entire FreeDi firmware itself?

**Comment by colin-small** [comment]
It worked! Simple power down and power on fixed it.

![image](https://github.com/user-attachments/assets/592bb34d-5c6e-4c69-9936-e1d51e6a8ec7)

**Comment by colin-small** [comment]
But now klipper isn't working. It fails repeatedly if I try to restart it.

![image](https://github.com/user-attachments/assets/be92f931-5b7d-4653-afdf-967212b4c948)

![image](https://github.com/user-attachments/assets/a5046d94-28bf-45b4-9e21-8f656e62fd1b)

**Comment by colin-small** [comment]
I restarted the firmware and now it seems to be working again.

**Comment by Phil1988** [comment]
Im glad its solved and was no bug :)

Summary:
Reboot twice

once for restarting all the services and the second was needed because your toolhead caused a small problem (this happens sometimes, also with stock qidi. its not the most robust connection).
