### ISSUE TITLE
[Request] Full Image Download

### ISSUE THREAD

**Issue by Unicorn3D** [Phil1988/FreeDi#4]
''I created an image with a fresh and pure system for y'all.
Unfortunetly its 7.28GB (~5.6GB when flahed, so 2.3GB free disk space). This exceeds the maximum file size here on github, so I cant share it with you. If you have an idea, how I can make it availible for you, reach out to me.''

Answer. You could upload the files to google drive and share the link?

would like to try it out. Thanks for your work

**Comment by Phil1988** [comment]
Even better!
Its already here in the "Releases" section.

I found a way, but forgot to update the wiki page.
Updated now:
[see here](https://github.com/Phil1988/FreeDi/wiki/Installation-guide-for-fresh-systems)

Please tell me how it worked out here after you made it :)

**Comment by Unicorn3D** [comment]
I found it but now I have the following problem. when I enter ls /dev/serial/by-id/* I get the following:ls: cannot access '/dev/serial/by-id/*': No such file or directory
mks@mkspi:~$

**Comment by Unicorn3D** [comment]
<img width="545" alt="Bildschirmfoto 2024-10-12 um 19 55 39" src="https://github.com/user-attachments/assets/41a1d223-f96b-4f64-886e-21dc9c8457d1">

**Comment by Unicorn3D** [comment]
here is the proof that it worked
![Uploading IMG_4641 2.PNG…]()

**Comment by Unicorn3D** [comment]
![Uploading IMG_4641 2.PNG…]()

**Comment by Unicorn3D** [comment]
![grafik](https://github.com/user-attachments/assets/693fd0d6-189d-4349-854e-d2fc4111edd8)

**Comment by Phil1988** [comment]
Lets check a few things please.

what does this return:
`lsusb`
and
`ls /dev/serial/by-path/*`

Please show me your [mcu MKS_THR] and [mcu] section.

Have you rebooted the system?

**Comment by Unicorn3D** [comment]
<img width="786" alt="Bildschirmfoto 2024-10-14 um 08 28 16" src="https://github.com/user-attachments/assets/6135532e-edc1-44a7-a215-9834ce390d26">

**Comment by Unicorn3D** [comment]
[moonraker.log](https://github.com/user-attachments/files/17360285/moonraker.log)
[klippy.log](https://github.com/user-attachments/files/17360286/klippy.log)

**Comment by Unicorn3D** [comment]
so. now i've redone everything. it's running again. then i heated the hotend, suddenly no more power. printer restarts, again no connection to the toolboard. can it be that the hotend is defective? i have installed v2.3 or something like that.

**Comment by Phil1988** [comment]
Yeap, the toolhead should have been visible via lsusb, which is not for you.
You should see a device "OpenMoko".
Most likely your cable to the toolhead or the board itself might be defective.

Maybe you can check that on your side (checking the wire connection).

**Comment by Unicorn3D** [comment]
but the toolhead works. i have checked everything... if i redo everything everything works again. Now I have restarted, the toolhead is not accessible again

**Comment by Unicorn3D** [comment]
as soon as i reflash the emmc everything works again

**Comment by Unicorn3D** [comment]
ok probably the toolhead board is broken. i have now installed another one that i still had there. that works. now i have one more question.
if i order the new board from qidi does it also work? that is a bit different. v1.2 

<img width="569" alt="grafik" src="https://github.com/user-attachments/assets/fbdd0845-afd0-419a-a685-64a7702b1c35">

**Comment by Phil1988** [comment]
In general other hardware is not a breaking thing for my software as it uses official moonraker API.
As long as your klipper config is working and you have every mandatory section included in your printer.cfg there should not be any problem.

So in short: 
This toolheadboard shouold work,

I am closing this issue now as your issue is not related to the software :)
