### ISSUE TITLE
[Bug] Start and End G-Code ORCA SLICER

### ISSUE THREAD

**Issue by Unicorn3D** [Phil1988/FreeDi#7]
What exactly do I have to enter as Start and End G-Code in Orca Slicer?

<img width="508" alt="Bildschirmfoto 2024-10-14 um 13 14 32" src="https://github.com/user-attachments/assets/cbd41a79-cf0f-45dd-be04-ec6bd1ced706">

**Comment by Phil1988** [comment]
Hello @Unicorn3D ,
I think this is getting out of hand :)

I am happily helping anyone with problems related to the software and also further related to the OS and klipper config.
But it seems as this is your first point of contact for any problems.
I can not give a non-profit "everything support" here ^^
I hope you understand it and you please only open issues in the future that are either totally related to my software or you cant fix after you really tried and searched for a solution yourself.

I didnt do anything fancy for Orca.

Start gcode
```
G28
G0 Z50 F600
M190 S[first_layer_bed_temperature]
G28 Z
G29 ; mesh bed leveling ,comment this code to close it
G0 X0 Y0 Z50 F6000
M109 S[first_layer_temperature]
M83
G0 Z5 F1200
G0 X{first_layer_print_min[0]} Y{max(0, first_layer_print_min[1] - 2)} F12000
G0 Z0.2 F600
G1 E3 F1800
G0 Z0.3 F600
G1 X{min(first_layer_print_min[0] + 30,print_bed_max[0])} E6 F600
```

End gcode:
`PRINT_END`

**Comment by Unicorn3D** [comment]
ok i understand thanks for your help. but that was just a question because the problem still occurs. it shows the following problem. isn't that due to the firmware?

**Comment by Unicorn3D** [comment]
it could have been that you are aware of the problem. we are now a total of 5 people who are experimenting with your firmware. as soon as i have found the problem i will let you know.

**Comment by Unicorn3D** [comment]
so it makes some mistake with the z offset. i have now set the minimum distance of stepper Z to a minus value so that i can set the first layer. maybe you will find out something in the future. but it does something wrong with the z offset. it is at 0 after setting and the nozzle is still 1.5mm away from the bed.
